services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/src/app
    depends_on:
      - db
    command: tail -F anything
    env_file:
      - .env
  db:
    image: postgres
    env_file:
      - .env